# Makefile used to build libraries
include ../../Makefile.inc

TARGETS = all clean
.PHONY: $(TARGETS)

all: DLDetection

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<
%.o: %.cc
	$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<

%.o: %.c
	$(CC) $(CXXFLAGS) $(INCLUDES) -o $@ -c $<

DLDetection: luaDLDetection.o \
	DarknetDetector.o
	$(LD) $(LDFLAGS) -o $@.$(SHLIBEXT) $(LIBOPTS) $^ $(LIB_DIR) -lm `pkg-config --libs opencv` -lturbojpeg -llua -ldarknet -lglog

clean:
	rm -f *.$(SHLIBEXT) *.o
